'use client';
import Link from 'next/link';
import { Brand, Empty, Icon, Photo, Tag } from '@/components/ui';
import { moveJob, type Job } from '@/lib/model';
import { downloadManifest } from '@/lib/download';
import { updateJob, useJobs } from './store';

export function Delivery({ jobs, onOpen, onMessage }: { jobs: Job[]; onOpen: (id: string) => void; onMessage: (message: string) => void }) {
  const ready = jobs.filter(j => j.stage === 4 && j.approved); const delivered = jobs.filter(j => j.stage === 5);
  function deliver(job: Job) {
    try { updateJob(job.id, current => moveJob(current, 5)); onMessage('Client handoff recorded locally. No files or messages were sent.'); }
    catch (e) { onMessage(e instanceof Error ? e.message : 'The handoff could not be recorded.'); }
  }
  return <><div className="workspace-heading"><div><span className="mono workspace-kicker">THE FINAL HANDOFF</span><h1>A good finish. All connected.</h1><p>Keep the approved work and the original job on the same page.</p></div><Tag tone="stage-5">{ready.length} READY FOR DELIVERY</Tag></div><div className="delivery-notice"><Icon name="info" /><p>This preview records a local handoff status only. It does not send messages, deliver media, or create a hosted customer gallery.</p></div><section className="delivery-section"><div className="delivery-section-heading"><h2>Ready for the handoff</h2><span className="count-badge">{ready.length}</span></div>{!ready.length ? <Empty title="Good work starts with a final look." icon="eye">Complete a job’s human review to prepare it for the client. <Link className="text-link" href="/workspace/review">Open media review<Icon name="arrow" /></Link></Empty> : <div className="delivery-grid">{ready.map(job => <DeliveryCard key={job.id} job={job} delivered={false} onOpen={onOpen} onDeliver={deliver} />)}</div>}</section><section className="delivery-section"><div className="delivery-section-heading"><h2>Delivered locally</h2><span className="count-badge">{delivered.length}</span></div>{!delivered.length ? <Empty title="No recorded handoffs yet.">Approved jobs will appear here after you mark them as delivered.</Empty> : <div className="delivery-grid">{delivered.map(job => <DeliveryCard key={job.id} job={job} delivered onOpen={onOpen} onDeliver={deliver} />)}</div>}</section></>;
}
function DeliveryCard({ job, delivered, onOpen, onDeliver }: { job: Job; delivered: boolean; onOpen: (id: string) => void; onDeliver: (job: Job) => void }) {
  return <article className="delivery-card"><div className="delivery-card-photo"><Photo alt={`Example property photo for ${job.address}`} /><Tag tone={delivered ? 'stage-5' : 'orange'}>{delivered ? 'Handoff recorded' : 'Human review approved'}</Tag><span className="mono">ILLUSTRATIVE PROPERTY</span></div><div className="delivery-card-content"><span className="mono muted">{job.id} · {job.city}</span><h3>{job.address}</h3><p>{job.client}</p><div className="service-tags">{job.services.map(service => <span key={service}>{service}</span>)}</div><div className="delivery-meta"><span><Icon name="folder" />{job.fileCount} file records</span><span><Icon name="checkCircle" />Human-reviewed</span></div><div className="delivery-card-actions">{delivered ? <Link className="button button-full" href={`/delivery/${job.id}`}>Open local delivery preview<Icon name="arrowUp" /></Link> : <button type="button" className="button button-accent button-full" onClick={() => onDeliver(job)}>Mark as delivered<Icon name="send" /></button>}<div><button className="text-link" type="button" onClick={() => onOpen(job.id)}>Job details<Icon name="arrow" /></button><button className="text-link" type="button" onClick={() => downloadManifest(job)}><Icon name="download" />Metadata manifest</button></div></div></div></article>;
}
export function DeliveryPortal({ id }: { id: string }) {
  const { jobs, persistent } = useJobs(); const job = jobs.find(j => j.id === id && j.stage === 5);
  return <><header className="portal-header container"><Brand /><Tag>LOCAL DELIVERY PREVIEW</Tag><Link href="/workspace/delivery" className="text-link">Back to workspace<Icon name="arrowUp" /></Link></header><main className="portal-page" id="main">{!job ? <div className="container"><Empty title="No local delivery for this job." icon="folder">This preview reads jobs from this browser only. A delivery-preview address is not a shareable client gallery. <Link className="button" href="/workspace/delivery">Back to deliveries<Icon name="arrow" /></Link></Empty></div> : <><div className="portal-hero"><Photo alt={`Illustrative exterior for ${job.address}`} priority /><div className="photo-shade" /><div className="container portal-hero-content"><span className="mono">NORTHLIGHT STUDIO · EXAMPLE WORKSPACE</span><h1>{job.address}</h1><p>{job.city}</p><Tag tone="stage-5">LOCAL HANDOFF RECORDED</Tag></div></div><div className="container portal-content"><div className="delivery-notice"><Icon name="info" /><p>Illustrative delivery preview. No media is hosted, uploaded, or available to download. This address works only with this browser’s sample data.{!persistent && ' Browser storage is unavailable; changes will be lost when this session ends.'}</p></div><div className="portal-summary"><div><span className="mono">THE PROPERTY PACKAGE</span><h2>Every detail, back together.</h2><p>Prepared for {job.client}</p><div className="service-tags">{job.services.map(service => <Tag key={service}>{service}</Tag>)}</div></div><div className="portal-download"><Icon name="folder" /><strong>{job.fileCount} file records</strong><p>Export the illustrative job metadata, not the media.</p><button type="button" className="button button-full" onClick={() => downloadManifest(job)}>Download metadata manifest<Icon name="download" /></button></div></div><div className="portal-records"><span className="mono">ATTACHED METADATA</span>{job.files.length ? job.files.map(file => <div className="portal-file" key={file.id}><Icon name="file" /><span>{file.name}</span><small>{(file.size / 1024 / 1024).toFixed(2)} MB · metadata only</small></div>) : <p>The seed job has an illustrative file count. No actual media files or individual upload records are included.</p>}</div></div></>}</main></>;
}
