'use client';
import Link from 'next/link';
import { useState, type FormEvent } from 'react';
import { Dialog, Icon, Photo, Status, Tabs, Tag } from '@/components/ui';
import { addActivity, createJob, DEMO_DATE, formatDate, formatTime, moveJob, SERVICES, STAGES, TEAM, validateJobInput, type Job, type JobInput, type Stage } from '@/lib/model';
import { download } from '@/lib/download';
import { insertJob, updateJob } from './store';

function JobForm({ initial, onSave, label }: { initial?: Job; onSave: (input: JobInput) => void; label: string }) {
  const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(''); setSaved(false);
    const data = new FormData(event.currentTarget);
    const field = (name: string) => String(data.get(name) ?? '');
    try {
      const input = validateJobInput({ address: field('address'), city: field('city'), client: field('client'), photographer: field('photographer'), date: field('date'), time: field('time'), notes: field('notes'), services: data.getAll('services').map(String) });
      onSave(input); setSaved(true);
    } catch (e) { setError(e instanceof Error ? e.message : 'The details could not be saved.'); }
  }
  return <form className="job-form" onSubmit={submit}><div className="form-grid"><div><label htmlFor="job-address">Property address <span>*</span></label><input id="job-address" name="address" required maxLength={160} defaultValue={initial?.address} placeholder="740 Ocean View Drive" /></div><div><label htmlFor="job-city">City / region <span>*</span></label><input id="job-city" name="city" required maxLength={160} defaultValue={initial?.city} placeholder="Malibu, CA" /></div></div><label htmlFor="job-client">Client / agency <span>*</span></label><input id="job-client" name="client" required maxLength={160} defaultValue={initial?.client} placeholder="Your client or agency" /><div className="form-grid"><div><label htmlFor="job-date">Shoot date <span>*</span></label><input id="job-date" name="date" type="date" required defaultValue={initial?.date || DEMO_DATE} /></div><div><label htmlFor="job-time">Shoot time <span>*</span></label><input id="job-time" name="time" type="time" required defaultValue={initial?.time || '09:00'} /></div></div><p className="field-help">Property-local time. This preview does not convert time zones.</p><label htmlFor="job-photographer">Photographer</label><select id="job-photographer" name="photographer" defaultValue={initial?.photographer || ''}><option value="">Unassigned — choose later</option>{TEAM.map(name => <option key={name}>{name}</option>)}</select><fieldset className="service-options"><legend>Services & add-ons <span>*</span></legend>{SERVICES.map(service => <label key={service}><input name="services" type="checkbox" value={service} defaultChecked={initial ? initial.services.includes(service) : service === 'Photography'} /><span>{service}</span></label>)}</fieldset><label htmlFor="job-notes">Shoot instructions</label><textarea id="job-notes" name="notes" rows={3} maxLength={4000} defaultValue={initial?.notes} placeholder="Access arrangements, shot priorities, and anything the team should know." /><span className="field-help">Sample information only. Do not add real access codes or confidential details.</span>{error && <p className="form-error" role="alert">{error}</p>}{saved && <p className="form-saved" role="status">Details saved in this browser.</p>}<button type="submit" className="button button-full">{label}<Icon name="check" /></button></form>;
}
export function NewJobDialog({ onClose, onCreated }: { onClose: () => void; onCreated: (job: Job) => void }) {
  return <Dialog title="New property job" onClose={onClose} wide><p className="dialog-intro">A connected start. Keep the property, people, and services together. This creates a sample job on this browser only.</p><JobForm label="Create property job" onSave={input => {
    const job = createJob(input, `PT-${crypto.randomUUID().slice(0, 8).toUpperCase()}`);
    insertJob(job); onCreated(job);
  }} /></Dialog>;
}
export function JobDialog({ job, onClose }: { job: Job; onClose: () => void }) {
  const [tab, setTab] = useState(0); const [message, setMessage] = useState('');
  function act(fn: () => void, text: string) { try { fn(); setMessage(text); } catch (e) { setMessage(e instanceof Error ? e.message : 'The change could not be saved.'); } }
  function brief() {
    download(`PHOTOTRACKLY — LOCAL PREVIEW JOB BRIEF\n\nFictional data and illustrative imagery. Not a live booking.\n\n${job.id}\n${job.address}, ${job.city}\nClient: ${job.client}\nShoot: ${job.date} ${job.time} (property-local time)\nPhotographer: ${job.photographer || 'Unassigned'}\nServices: ${job.services.join(', ')}\n\n${job.notes}`, 'text/plain', `${job.id}-preview-brief.txt`);
  }
  return <Dialog title={job.address} onClose={onClose} drawer><div className="drawer-hero"><Photo alt={`Illustrative property photograph for ${job.address}`} /><span className="mono">{job.id} · EXAMPLE PROPERTY IMAGE</span></div><div className="drawer-summary"><span><Icon name="pin" />{job.city}</span><Status job={job} /><button className="text-link" type="button" onClick={brief}><Icon name="download" />Download brief</button></div><Tabs labels={['Overview', 'File records', 'Activity']} index={tab} onChange={setTab} prefix="job" label="Property job details" className="drawer-tabs" /><div id="job-panel" role="tabpanel" aria-labelledby={`job-tab-${tab}`} className="drawer-body">
    {tab === 0 && <><div className="drawer-data-grid"><div><span className="mono">CLIENT / AGENCY</span><strong>{job.client}</strong></div><div><span className="mono">SHOOT</span><strong>{formatDate(job.date)} · {formatTime(job.time)}</strong></div></div>{job.stage === 5 ? <div className="prose"><p>{job.notes}</p><div className="service-tags">{job.services.map(s => <Tag key={s}>{s}</Tag>)}</div><p>This handoff is recorded as delivered. Move back to review to reopen the job before changing the brief or file records.</p><Link href={`/delivery/${job.id}`} className="button button-outline">Open local delivery preview<Icon name="arrowUp" /></Link></div> : <JobForm key={job.id} initial={job} label="Save job details" onSave={input => updateJob(job.id, current => addActivity({ ...current, ...input, approved: false, checks: [false, false, false, false] }, 'Job details updated. Human review must be reconfirmed before delivery.'))} />}</>}
    {tab === 1 && <><div className="file-summary"><span className="feature-icon"><Icon name="folder" /></span><div><strong>{job.fileCount} file records</strong><span>Metadata attached to this property job</span></div></div><label className={`file-drop ${job.stage === 5 ? 'disabled' : ''}`}><Icon name="upload" /><strong>Add source-file records</strong><span>Choose files to record their names and sizes</span><input type="file" multiple disabled={job.stage === 5} aria-label="Add source-file records" onChange={event => {
      const files = Array.from(event.target.files || []);
      event.target.value = '';
      if (!files.length) return;
      act(() => updateJob(job.id, current => {
        if (current.stage === 5) throw new Error('Reopen the job before changing file records.');
        if (current.files.length + files.length > 500) throw new Error('The preview supports up to 500 attached metadata records per job.');
        const records = files.map(file => ({ id: crypto.randomUUID(), name: file.name.slice(0, 500), size: file.size, type: file.type.slice(0, 200) }));
        return addActivity({ ...current, files: [...current.files, ...records], fileCount: current.fileCount + records.length, approved: false, checks: [false, false, false, false] }, `${records.length} local file metadata record(s) attached. No file contents uploaded.`);
      }), 'File metadata added locally. No file contents were uploaded.');
    }} /></label><p className="file-privacy"><Icon name="lock" />This preview saves names and sizes only. It does not read, upload, retain, or deliver file contents. The sample count may include illustrative files that are not listed below.</p><div className="file-list">{job.files.map(file => <div key={file.id}><Icon name="file" /><span><strong>{file.name}</strong><small>{(file.size / 1024 / 1024).toFixed(2)} MB · metadata only</small></span><button type="button" className="icon-button" aria-label={`Remove ${file.name}`} disabled={job.stage === 5} onClick={() => act(() => updateJob(job.id, current => addActivity({ ...current, files: current.files.filter(f => f.id !== file.id), fileCount: Math.max(0, current.fileCount - 1), approved: false, checks: [false, false, false, false] }, `Removed file metadata: ${file.name}`)), 'File record removed from this browser.')}><Icon name="close" /></button></div>)}</div></>}
    {tab === 2 && <div className="activity-list">{job.activity.map((item, i) => <div key={`${item.time}-${i}`}><span className="activity-dot" /><p>{item.text}<small>{new Date(item.time).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: 'UTC' })} UTC</small></p></div>)}</div>}
  </div><div className="drawer-bottom"><label htmlFor="job-stage">WORKFLOW STAGE</label><select id="job-stage" value={job.stage} onChange={event => act(() => updateJob(job.id, current => moveJob(current, Number(event.target.value) as Stage)), 'Workflow stage updated locally.')} >{STAGES.map((stage, i) => <option key={stage.name} value={i}>{stage.name}</option>)}</select><span className="field-help">Move forward one step at a time. Reopening earlier stages clears approval.</span>{message && <p className="drawer-message" role="status">{message}</p>}{job.stage === 4 && !job.approved ? <Link className="button button-full" href="/workspace/review" onClick={onClose}>Open human review<Icon name="arrow" /></Link> : job.stage < 5 && <button type="button" className="button button-full" onClick={() => act(() => updateJob(job.id, current => moveJob(current, (current.stage + 1) as Stage)), job.stage === 4 ? 'Client handoff recorded locally. No message or files were sent.' : 'Job moved to the next stage.')} >{job.stage === 4 ? 'Mark as delivered locally' : `Next: ${STAGES[job.stage + 1].name}`}<Icon name="arrow" /></button>}</div></Dialog>;
}
