'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Empty, Icon, Photo, Status, Tag } from '@/components/ui';
import { addActivity, approveJob, requestRevision, REVIEW_CHECKS, type Job } from '@/lib/model';
import { updateJob } from './store';

export function Review({ jobs, onOpen, onMessage }: { jobs: Job[]; onOpen: (id: string) => void; onMessage: (message: string) => void }) {
  const [selected, setSelected] = useState('PT-0842');
  const queue = jobs.filter(j => j.stage === 4); const job = queue.find(j => j.id === selected) || queue[0];
  return <><div className="workspace-heading"><div><span className="mono workspace-kicker">A CONSIDERED FINAL LOOK</span><h1>Good work, ready to go.</h1><p>A human review. Specific feedback. A clear path to the client.</p></div><Tag>{queue.filter(j => !j.approved).length} AWAITING REVIEW</Tag></div>{!job ? <Empty title="The review queue is clear." icon="checkCircle">Move a job from editing into review to see it here. <Link className="text-link" href="/workspace/pipeline">Open the job pipeline<Icon name="arrow" /></Link></Empty> : <div className="review-layout"><aside className="review-queue" aria-label="Review queue"><div className="review-queue-heading"><span className="mono">REVIEW QUEUE</span><span className="count-badge">{queue.length}</span></div>{queue.map(item => <button type="button" className={`review-queue-item ${item.id === job.id ? 'active' : ''}`} key={item.id} onClick={() => setSelected(item.id)}><Photo alt={`Illustrative image for ${item.address}`} /><span className="mono">{item.id}</span><strong>{item.address}</strong><small>{item.city}</small><span className="review-queue-files"><Icon name="folder" />{item.fileCount} file records</span><Status job={item} /></button>)}</aside><ReviewPanel key={job.id} job={job} onOpen={onOpen} onMessage={onMessage} /></div>}</>;
}
function ReviewPanel({ job, onOpen, onMessage }: { job: Job; onOpen: (id: string) => void; onMessage: (message: string) => void }) {
  const [zoom, setZoom] = useState(1); const [note, setNote] = useState(''); const [error, setError] = useState('');
  const completed = job.checks.filter(Boolean).length;
  function act(fn: () => void, text: string) { try { fn(); setError(''); onMessage(text); } catch (e) { setError(e instanceof Error ? e.message : 'The review could not be saved.'); } }
  return <div className="review-work"><div className="review-property-detail"><div><span className="mono">{job.id} / HUMAN QUALITY REVIEW</span><h2>{job.address}</h2><p>{job.client} · {job.services.join(' + ')}</p></div><button className="button button-outline button-small" type="button" onClick={() => onOpen(job.id)}>Property brief<Icon name="arrowUp" /></button></div><div className="review-content"><div className="review-canvas"><div className="review-image-toolbar"><span className="mono">REFERENCE EXTERIOR · PREVIEW ONLY</span><div className="zoom-buttons"><button type="button" className="icon-button" aria-label="Zoom out" disabled={zoom <= 1} onClick={() => setZoom(Math.max(1, zoom - 0.25))}><Icon name="minus" /></button><button type="button" className="zoom-value" aria-label="Reset image zoom" onClick={() => setZoom(1)}>{Math.round(zoom * 100)}%</button><button type="button" className="icon-button" aria-label="Zoom in" disabled={zoom >= 2} onClick={() => setZoom(Math.min(2, zoom + 0.25))}><Icon name="plus" /></button></div></div><div className="review-image"><div className="review-image-transform" style={{ transform: `scale(${zoom})` }}><Photo alt="Illustrative property exterior used as a reference for the manual review preview" priority /></div><div className="viewfinder-corner corner-a" /><div className="viewfinder-corner corner-b" /><span className="review-image-label mono">ILLUSTRATIVE REFERENCE · NOT AN UPLOADED ASSET</span></div><div className="review-honesty"><Icon name="info" /><span>This reference image demonstrates the review interface. No source images are uploaded or automatically inspected in this preview.</span></div></div><aside className="review-checklist"><span className="mono">YOUR FINAL LOOK</span><h3>Review checklist</h3><p>Record your review, one decision at a time.</p><div className="review-progress"><span>{completed} of 4 checked</span><div><span style={{ width: `${completed * 25}%` }} /></div></div><div className="review-check-items">{REVIEW_CHECKS.map((label, i) => <label key={label}><input type="checkbox" checked={job.checks[i]} onChange={event => {
    const checked = event.target.checked;
    act(() => updateJob(job.id, current => addActivity({ ...current, checks: current.checks.map((v, index) => index === i ? checked : v), approved: false }, `${label}: ${checked ? 'checked' : 'reopened'} by reviewer.`)), 'Manual review checklist saved in this browser.');
  }} /><span>{label}</span></label>)}</div><p className="field-help">These are your decisions, not automated image checks.</p>{error && <p className="form-error" role="alert">{error}</p>}<button type="button" className="button button-full approve-button" disabled={completed !== 4 || job.approved} onClick={() => act(() => updateJob(job.id, approveJob), 'Review approved locally. The job is ready for a recorded client handoff.')}><Icon name="checkCircle" />{job.approved ? 'Approved for delivery' : 'Approve for delivery'}</button>{job.approved && <Link href="/workspace/delivery" className="text-link delivery-next">Go to client delivery<Icon name="arrow" /></Link>}<div className="revision-box"><label htmlFor="revision-notes">Need another look?</label><textarea id="revision-notes" aria-label="Revision notes" rows={3} maxLength={2000} placeholder="Add clear, specific feedback for the editor…" value={note} onChange={e => setNote(e.target.value)} /><button type="button" className="button button-outline button-full" disabled={!note.trim()} onClick={() => act(() => updateJob(job.id, current => requestRevision(current, note)), 'Revision note saved. This job has returned to editing.')}><Icon name="repeat" />Request revisions</button></div></aside></div></div>;
}
