'use client';
import { useState } from 'react';
import { Avatar, Empty, Icon, Photo, Status, Toast } from '@/components/ui';
import { DEMO_DATE, formatDate, formatTime, jobsCsv, moveJob, STAGES, TEAM, validDate, type Job, type Stage, type View } from '@/lib/model';
import { download } from '@/lib/download';
import { JobDialog, NewJobDialog } from './job-dialog';
import { updateJob, useJobs } from './store';
import { Review } from './review';
import { Delivery } from './delivery';

export function Heading({ kicker, title, copy, onNew }: { kicker: string; title: string; copy: string; onNew?: () => void }) {
  return <div className="workspace-heading"><div><span className="mono workspace-kicker">{kicker}</span><h1>{title}</h1><p>{copy}</p></div>{onNew && <button type="button" className="button button-accent" onClick={onNew}><Icon name="plus" />New property job</button>}</div>;
}
function Metric({ icon, label, value, note, tone = '' }: { icon: string; label: string; value: number; note: string; tone?: string }) {
  return <div className={`app-metric ${tone}`}><div><span>{label}</span><Icon name={icon} /></div><strong>{String(value).padStart(2, '0')}</strong><span className="metric-note">{note}</span></div>;
}
export default function Workspace({ view }: { view: View }) {
  const { jobs } = useJobs(); const [modal, setModal] = useState<string | null>(null); const [message, setMessage] = useState('');
  const selected = jobs.find(job => job.id === modal);
  return <>
    {view === 'pipeline' && <Pipeline jobs={jobs} onOpen={setModal} onMessage={setMessage} />}
    {view === 'schedule' && <Schedule jobs={jobs} onOpen={setModal} />}
    {view === 'review' && <Review jobs={jobs} onOpen={setModal} onMessage={setMessage} />}
    {view === 'delivery' && <Delivery jobs={jobs} onOpen={setModal} onMessage={setMessage} />}
    {modal === 'new' && <NewJobDialog onClose={() => setModal(null)} onCreated={job => { setModal(job.id); setMessage('Property job created in this browser.'); }} />}
    {selected && <JobDialog key={selected.id} job={selected} onClose={() => setModal(null)} />}
    {message && <Toast message={message} onClose={() => setMessage('')} />}
  </>;
}
function JobCard({ job, onOpen }: { job: Job; onOpen: (id: string) => void }) {
  return <button type="button" className={`job-card crop-${Number(job.id.slice(-1)) % 3}`} data-testid={`job-${job.id}`} aria-label={`Open job ${job.address}`} draggable onDragStart={event => { event.dataTransfer.setData('text/plain', job.id); event.dataTransfer.effectAllowed = 'move'; }} onClick={() => onOpen(job.id)}><span className="job-card-image"><Photo alt={`Example property image for ${job.address}`} /><span className="job-id mono">{job.id}</span>{job.approved && <span className="job-approved"><Icon name="check" /></span>}</span><span className="job-card-content"><span className="job-location"><Icon name="pin" />{job.city}</span><strong className="job-address">{job.address}</strong><span className="job-client">{job.client}</span><span className="job-service-tags">{job.services.slice(0, 2).map(s => <span key={s}>{s}</span>)}{job.services.length > 2 && <span>+{job.services.length - 2}</span>}</span><span className="job-card-person"><Avatar name={job.photographer} small />{job.photographer || 'Assign a photographer'}</span><span className="job-card-footer"><span><Icon name="calendar" />{formatDate(job.date)}</span><span><Icon name={job.stage < 2 ? 'clock' : 'folder'} />{job.stage < 2 ? formatTime(job.time) : `${job.fileCount} files`}</span></span></span></button>;
}
function Pipeline({ jobs, onOpen, onMessage }: { jobs: Job[]; onOpen: (id: string) => void; onMessage: (message: string) => void }) {
  const [query, setQuery] = useState(''); const [member, setMember] = useState(''); const [stage, setStage] = useState(''); const [layout, setLayout] = useState<'board' | 'table'>('board'); const [drop, setDrop] = useState<number | null>(null);
  const q = query.trim().toLowerCase();
  const filtered = jobs.filter(job => (!q || `${job.id} ${job.address} ${job.city} ${job.client}`.toLowerCase().includes(q)) && (!member || (member === 'unassigned' ? !job.photographer : job.photographer === member)) && (stage === '' || job.stage === Number(stage)));
  return <><Heading kicker="YOUR STUDIO, IN FOCUS" title="A clearer view of your day." copy="Every job. Every handoff. Right where you need it." onNew={() => onOpen('new')} /><div className="app-metrics"><Metric icon="folder" label="Active jobs" value={jobs.filter(j => j.stage < 5).length} note="From booking through review" /><Metric icon="calendar" label="Scheduled shoots" value={jobs.filter(j => j.stage === 1).length} note="A person and a time in place" /><Metric icon="eye" label="Needs review" value={jobs.filter(j => j.stage === 4 && !j.approved).length} note="Ready for a considered look" tone="metric-orange" /><Metric icon="checkCircle" label="Delivered" value={jobs.filter(j => j.stage === 5).length} note="The final handoff, recorded" tone="metric-teal" /></div>
  <section className="jobs-section" aria-labelledby="property-jobs-title"><div className="jobs-section-top"><h2 id="property-jobs-title">Property jobs <span className="count-badge">{filtered.length}</span></h2><div><button type="button" className="text-link" onClick={() => download(jobsCsv(filtered), 'text/csv;charset=utf-8', 'phototrackly-jobs.csv')}><Icon name="download" />Export jobs</button><div className="view-toggle" aria-label="Job layout"><button type="button" className="icon-button" aria-label="Board view" aria-pressed={layout === 'board'} onClick={() => setLayout('board')}><Icon name="board" /></button><button type="button" className="icon-button" aria-label="Table view" aria-pressed={layout === 'table'} onClick={() => setLayout('table')}><Icon name="list" /></button></div></div></div><div className="filter-bar"><label className="search-field"><Icon name="search" /><input type="search" aria-label="Search jobs" placeholder="Search properties, clients, or job IDs…" value={query} onChange={e => setQuery(e.target.value)} /></label><select aria-label="Filter by photographer" value={member} onChange={e => setMember(e.target.value)}><option value="">All photographers</option><option value="unassigned">Unassigned</option>{TEAM.map(name => <option key={name}>{name}</option>)}</select><select aria-label="Filter by stage" value={stage} onChange={e => setStage(e.target.value)}><option value="">All stages</option>{STAGES.map((s, i) => <option value={i} key={s.name}>{s.name}</option>)}</select></div>
  {!filtered.length ? <Empty title="No jobs match those filters." icon="search">Try a different property, client, photographer, or stage. <button className="text-link" type="button" onClick={() => { setQuery(''); setMember(''); setStage(''); }}>Clear filters</button></Empty> : layout === 'board' ? <div className="kanban-board">{STAGES.map((s, i) => <section className={`kanban-column ${drop === i ? 'drag-over' : ''}`} key={s.name} aria-label={`${s.name} jobs`} data-testid={`stage-${i}`} onDragOver={event => { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; setDrop(i); }} onDragLeave={event => { if (!event.currentTarget.contains(event.relatedTarget as Node | null)) setDrop(null); }} onDrop={event => {
    event.preventDefault(); setDrop(null);
    const id = event.dataTransfer.getData('text/plain');
    try { updateJob(id, job => moveJob(job, i as Stage)); onMessage(`Job is now in ${s.name}. This change is local only.`); }
    catch (e) { onMessage(e instanceof Error ? e.message : 'The job could not be moved.'); }
  }}><div className="kanban-heading"><span className={`dot stage-dot-${i}`} /><h3>{s.name}</h3><span className="count-badge">{filtered.filter(j => j.stage === i).length}</span><Icon name={s.icon} /></div>{filtered.filter(j => j.stage === i).map(job => <JobCard job={job} key={job.id} onOpen={onOpen} />)}{!filtered.some(j => j.stage === i) && <div className="empty-column">No jobs here yet</div>}</section>)}</div> : <div className="table-scroll"><table className="job-table"><thead><tr>{['Property', 'Client', 'Stage', 'Photographer', 'Shoot date', 'Services'].map(title => <th key={title} scope="col">{title}</th>)}</tr></thead><tbody>{filtered.map(job => <tr key={job.id}><td><button className="table-property" type="button" onClick={() => onOpen(job.id)}><strong>{job.address}</strong><span>{job.id} · {job.city}</span></button></td><td>{job.client}</td><td><Status job={job} /></td><td><span className="table-person"><Avatar name={job.photographer} small />{job.photographer || 'Unassigned'}</span></td><td>{formatDate(job.date)}<small>{formatTime(job.time)}</small></td><td>{job.services.join(', ')}</td></tr>)}</tbody></table></div>}
  </section></>;
}
function Schedule({ jobs, onOpen }: { jobs: Job[]; onOpen: (id: string) => void }) {
  const [date, setDate] = useState(DEMO_DATE);
  const day = jobs.filter(j => j.date === date && j.stage !== 5).sort((a, b) => a.time.localeCompare(b.time));
  const unassigned = day.filter(j => !j.photographer);
  function step(offset: number) { const next = new Date(`${date}T12:00:00Z`); next.setUTCDate(next.getUTCDate() + offset); setDate(next.toISOString().slice(0, 10)); }
  return <><Heading kicker="THE SHOOT DAY, TOGETHER" title="A place for everyone." copy="See who is going where, and what they need to know." onNew={() => onOpen('new')} /><div className="schedule-toolbar"><div><h2>{new Date(`${date}T12:00:00Z`).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', timeZone: 'UTC' })}</h2><p>{day.length} sample shoot{day.length === 1 ? '' : 's'} · Property-local times, not converted across time zones</p></div><div className="schedule-date-controls"><button type="button" className="icon-button" aria-label="Previous day" onClick={() => step(-1)}><Icon name="chevron" className="flip" /></button><input aria-label="Schedule date" type="date" value={date} onChange={e => { if (validDate(e.target.value)) setDate(e.target.value); }} /><button type="button" className="icon-button" aria-label="Next day" onClick={() => step(1)}><Icon name="chevron" /></button><button className="button button-outline button-small" type="button" onClick={() => setDate(DEMO_DATE)}>Sample day</button></div></div>
  {unassigned.length > 0 && <div className="unassigned-tray"><Icon name="user" /><span><strong>{unassigned.length} job{unassigned.length === 1 ? '' : 's'} need a photographer</strong><small>Assign the right person manually from the property brief.</small></span>{unassigned.map(job => <button type="button" className="button button-outline button-small" key={job.id} onClick={() => onOpen(job.id)}>{job.address}<Icon name="arrow" /></button>)}</div>}
  {!day.length ? <Empty title="A little breathing room." icon="calendar">No sample shoots on this date. Choose another day or create a new property job.</Empty> : <div className="schedule-lanes">{TEAM.map(name => <section className="schedule-lane" key={name}><div className="schedule-lane-heading"><Avatar name={name} /><div><h3>{name}</h3><span>{day.filter(j => j.photographer === name).length} assigned shoots</span></div></div><div className="schedule-items">{day.filter(j => j.photographer === name).map(job => <button type="button" key={job.id} className={`schedule-event stage-event-${job.stage}`} onClick={() => onOpen(job.id)}><span className="mono"><Icon name="clock" />{formatTime(job.time)}</span><strong>{job.address}</strong><span><Icon name="pin" />{job.city}</span><span className="schedule-services">{job.services.join(' · ')}</span><Status job={job} /><span className="event-open">Open property brief<Icon name="arrowUp" /></span></button>)}{!day.some(j => j.photographer === name) && <div className="empty-lane"><Icon name="calendar" /><span>No shoots assigned</span></div>}</div></section>)}</div>}
  </>;
}
