import Link from 'next/link';
import Navigation from '@/components/prelaunch/navigation';
import { Concept, Glyph, JoinLink, Kicker, Wordmark } from '@/components/prelaunch/primitives';
import { Media } from '@/components/prelaunch/media';
import LeadForm from '@/components/prelaunch/lead-form';
import SampleJob from '@/components/prelaunch/sample-job';
import ProductionBoard from '@/components/prelaunch/production-board';
import FAQ from '@/components/prelaunch/faq';
import AnalyticsConsent, { CookieSettingsButton } from '@/components/prelaunch/analytics-consent';
import './prelaunch.css';

const journey = [
  ['order', 'Create the job', 'Bring the client, property, services, and access notes into one shared brief.'],
  ['calendar', 'Plan the shoot', 'Set the time, manually assign the photographer, and make the instructions clear.'],
  ['folder', 'Move through production', 'Keep source files, editing, feedback, and review connected to the property.'],
  ['delivery', 'Deliver approved media', 'See what is approved and ready before the final client handoff.'],
];
const workspace = [
  ['order', 'Orders & configurable services', 'Capture the brief once. Keep service packages, add-ons, client details, and property instructions together.'],
  ['calendar', 'Scheduling & manual assignments', 'Plan the shoot and give it a named owner. Keep timing and instructions attached to the job.'],
  ['folder', 'Files & production', 'Follow source materials, editing work, and the next handoff without losing the original context.'],
  ['review', 'Review & client delivery', 'Make revision notes and approvals visible, so everyone knows what is ready for the client.'],
];
export default function Landing() {
  return <div className="pl"><Navigation /><main id="main">
    <section className="pl-hero"><div className="pl-wrap pl-hero-grid"><div className="pl-hero-copy"><div className="pl-hero-top"><span className="pl-prelaunch"><span />In development</span><span>FOR PROPERTY MEDIA TEAMS · US & AU</span></div><h1>One tool for the<br /><em>whole</em> property<br />media job.</h1><p className="pl-hero-description">From the first order to the final files. We’re building one shared workspace for the brief, the people, and every handoff in between.</p><LeadForm variant="hero" /><a className="pl-explore" href="#sample-job" data-track="cta_click" data-location="hero_sample">Follow a sample job<Glyph name="down" /></a></div><div className="pl-hero-visual"><div className="pl-hero-photo"><Media name="interior" alt="Sunlit property interior with a neutral sofa, timber furniture, and large windows opening toward the garden" sizes="(max-width: 760px) 100vw, 50vw" priority /><div className="pl-hero-photo-top"><span>LESS CHASING.<br />MORE IN THE PICTURE.</span><span className="pl-focus-mark"><Glyph name="camera" /></span></div><span className="pl-hero-photo-caption">THE WORK IS BEAUTIFUL.<br />THE WORKFLOW SHOULD BE CLEAR.</span></div><div className="pl-floating-job"><div className="pl-floating-top"><Concept>Illustrative job</Concept><span className="pl-status"><span />In production</span></div><h2>42 Bay Street</h2><p>Photography · Drone · Floor plan</p><div className="pl-mini-stages">{['Booked', 'Shot', 'Editing', 'Review'].map((s, i) => <div key={s} className={i < 2 ? 'done' : i === 2 ? 'active' : ''}><span>{i < 2 ? <Glyph name="check" /> : `0${i + 1}`}</span><small>{s}</small></div>)}</div><div className="pl-floating-owner"><span className="pl-person">JA</span><span><strong>Jamie · Editor</strong><small>Next: send photo edits for review</small></span><Glyph name="arrow" /></div></div><span className="pl-hero-margin-note">ONE JOB RECORD. NO LOST CONTEXT.</span></div></div></section>
    <section className="pl-workflow-strip" aria-label="The connected property media workflow"><div className="pl-wrap"><p>One workspace.<br /><strong>Every step connected.</strong></p><ol>{[['order', 'Orders'], ['calendar', 'Schedule'], ['team', 'Team'], ['folder', 'Production'], ['delivery', 'Delivery']].map(([icon, name], i) => <li key={name}><Glyph name={icon} /><span>{name}</span>{i < 4 && <Glyph name="arrow" className="pl-strip-arrow" />}</li>)}</ol></div></section>
    <section className="pl-section pl-problems"><div className="pl-wrap"><div className="pl-section-heading"><div><Kicker>SOUND FAMILIAR?</Kicker><h2>The shoot is only<br /><em>part of the job.</em></h2></div><p>It’s the work between the work that fills the day.<br />The details to find. The files to chase. The status to check.</p></div><div className="pl-problem-grid"><article><span className="pl-problem-number">01 <span>BEFORE THE SHOOT</span></span><div className="pl-problem-quote"><Glyph name="pin" />“Where are the access notes?”</div><h3>Details arrive in pieces.</h3><p>The address is in an email. The time is on a calendar. The new instructions are in a message the photographer hasn’t seen.</p><div className="pl-problem-resolution"><Glyph name="arrow" /><span>A shared brief, not a scavenger hunt.</span></div></article><article><span className="pl-problem-number">02 <span>IN PRODUCTION</span></span><div className="pl-problem-quote"><Glyph name="folder" />“Did the editor get the files?”</div><h3>The next handoff goes quiet.</h3><p>Photos, drone footage, and floor plans move through different hands. Without a named next step, the work can sit and wait.</p><div className="pl-problem-resolution"><Glyph name="arrow" /><span>A visible owner for the next action.</span></div></article><article><span className="pl-problem-number">03 <span>BEFORE DELIVERY</span></span><div className="pl-problem-quote"><Glyph name="review" />“Which version is approved?”</div><h3>Ready is hard to recognize.</h3><p>Feedback lives in one thread, revisions in another. The coordinator has to piece it all together before the client gets the right files.</p><div className="pl-problem-resolution"><Glyph name="arrow" /><span>Clear review status before delivery.</span></div></article></div></div></section>
    <section className="pl-section pl-journey" id="how-it-works"><div className="pl-wrap"><div className="pl-centered-heading"><Kicker>THE JOB JOURNEY</Kicker><h2>Different hands.<br /><em>The same shared picture.</em></h2><p>The plan is simple: let the context travel with the property job,<br className="pl-desktop-break" /> from the first request to the final handoff.</p></div><ol className="pl-journey-steps">{journey.map(([icon, title, copy], i) => <li key={title}><div className="pl-journey-icon"><Glyph name={icon} /><span>0{i + 1}</span></div><h3>{title}</h3><p>{copy}</p></li>)}</ol><div className="pl-people-photos"><figure><div className="pl-people-photo"><Media name="photographer" alt="Property photographer operating a camera stabilizer inside a bright home during an on-site shoot" sizes="(max-width: 760px) 100vw, 50vw" /><span className="pl-image-label"><Glyph name="camera" />ON SITE</span></div><figcaption><span>01 / AT THE PROPERTY</span><h3>The right brief. Before the front door.</h3><p>Property details, services, and shoot instructions together.</p></figcaption></figure><figure><div className="pl-people-photo"><Media name="editor" alt="A property media team member reviewing photographs and a floor plan at a dual-monitor workstation" sizes="(max-width: 760px) 100vw, 50vw" /><span className="pl-image-label"><Glyph name="review" />IN PRODUCTION</span></div><figcaption><span>02 / BACK AT THE STUDIO</span><h3>The next handoff. Without the guesswork.</h3><p>Files, feedback, and a clear owner for what happens next.</p></figcaption></figure></div></div></section>
    <section className="pl-section pl-workspace" id="workspace"><div className="pl-wrap pl-workspace-grid"><div className="pl-workspace-visual"><Media name="exterior" alt="Contemporary residential exterior with timber decking, a covered terrace, and landscaped planting" sizes="(max-width: 760px) 100vw, 45vw" /><span className="pl-image-label">THE WORK BEHIND EVERY LISTING</span><div><span className="pl-overline">ONE CONNECTED WORKSPACE</span><h3>Keep the property<br />at the center.</h3><Concept>Planned product</Concept></div></div><div className="pl-workspace-copy"><Kicker>WHAT WE’RE BUILDING</Kicker><h2>Less switching tools.<br /><em>More shared context.</em></h2><p>You shouldn’t have to reconstruct a job to find the answer. The planned workspace brings its details, people, materials, and next action together.</p><div className="pl-feature-list">{workspace.map(([icon, title, copy]) => <article key={title}><span><Glyph name={icon} /></span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><p className="pl-workspace-note">First-release priorities, not a promise of features available today.</p></div></div></section>
    <SampleJob /><ProductionBoard />
    <section className="pl-editorial"><Media name="twilight" alt="Architectural property photograph of a modern two-story home with warm interior lighting beside a pool at dusk" sizes="100vw" /><div className="pl-wrap"><span className="pl-overline">A WORKSPACE FOR THE WORK BEHIND THE IMAGE</span><h2>Beautiful media.<br /><em>A clearer way to get there.</em></h2><p>Fewer lost details. Clearer handoffs.<br />Less time chasing the status of a job.</p></div></section>
    <FAQ />
    <section className="pl-section pl-early" id="early-access"><div className="pl-wrap pl-early-grid"><div className="pl-early-copy"><Kicker>HELP SHAPE PHOTOTRACKLY</Kicker><h2>A better workflow<br />starts with<br /><em>your real workday.</em></h2><p>We’re inviting owners and coordinators at growing property media teams in the United States and Australia to help shape the first release.</p><p>Tell us where your jobs get stuck. Your input will help us decide what to build first.</p><div className="pl-early-perks"><span><Glyph name="check" />Free to register</span><span><Glyph name="check" />No payment details</span><span><Glyph name="check" />No mandatory sales call</span></div><div className="pl-early-aside"><Glyph name="team" /><p><strong>Is this your team?</strong>You’re coordinating multiple shoots, people, or production handoffs—and you’re tired of reconstructing the story from separate tools.</p></div><span className="pl-prelaunch"><span />In development · Access is not immediate</span></div><div className="pl-early-card"><LeadForm variant="footer" /></div></div></section>
  </main><footer className="pl-footer"><div className="pl-wrap"><div><Wordmark /><p>Property media work, connected.</p></div><div><span>In development. Built for the work ahead.</span><div><Link href="/privacy">Privacy notice</Link><CookieSettingsButton /><a href="#main">Back to top<Glyph name="arrow" /></a></div><small>© {new Date().getFullYear()} PhotoTrackly</small></div></div></footer><AnalyticsConsent /></div>;
}
