import Link from 'next/link';
import Navigation from '@/components/prelaunch/navigation';
import { Wordmark } from '@/components/prelaunch/primitives';
import { Media } from '@/components/prelaunch/media';
import LeadForm from '@/components/prelaunch/lead-form';
import SampleJob from '@/components/prelaunch/sample-job';
import ProductionBoard from '@/components/prelaunch/production-board';
import FAQ from '@/components/prelaunch/faq';
import AnalyticsConsent, { CookieSettingsButton } from '@/components/prelaunch/analytics-consent';
import './prelaunch.css';
import './seo-page.css';

export default function Landing() {
  return <div className="pl reference-site"><Navigation /><main id="main">
    <section className="rf-hero rf-wrap pl-hero"><div className="rf-hero-copy"><p className="rf-eyebrow">FOR REAL ESTATE MEDIA TEAMS · US &amp; AUSTRALIA</p><h1>One tool for the whole <em>property media job.</em></h1><p className="rf-lead">We’re building PhotoTrackly to bring orders, scheduling, assignments, files, production, review and client delivery into one workspace. Your team can see what each job needs next without piecing together messages, calendars and folders.</p><LeadForm variant="hero" /><div className="rf-hero-secondary"><a className="rf-underline" href="#sample-job" data-track="cta_click" data-location="hero_sample">Explore a sample job ↓</a><span>In development · No payment or meeting required</span></div></div><div className="rf-hero-media"><Media name="interior" alt="Sunlit residential interior representing property media work" sizes="(max-width: 900px) 100vw, 50vw" priority /><div className="rf-job-card"><div><span className="rf-overline">ILLUSTRATIVE JOB</span><span className="rf-badge">In production</span></div><strong>42 Bay Street</strong><p>Photography · Drone · Floor plan</p><div className="rf-job-progress"><span className="rf-done">Booked</span><span className="rf-done">Shot</span><span className="rf-active">Editing</span><span>Review</span></div></div></div></section>
    <section className="rf-strip"><div className="rf-wrap rf-strip-inner"><p>One workspace. Every step of the job.</p><span>Orders</span><span>Schedule</span><span>Team</span><span>Production</span><span>Delivery</span></div></section>
    <section className="rf-section rf-friction" id="problems"><div className="rf-wrap"><div className="rf-section-head"><div><p className="rf-eyebrow">THE EVERYDAY BOTTLENECKS</p><h2>The shoot is only one part of the job.</h2></div><p>As orders grow, the work between booking and delivery can become the hardest part to coordinate.</p></div><div className="rf-friction-grid"><article><span>01 / BEFORE THE SHOOT</span><h3>Details arrive in pieces</h3><p>Access instructions, service choices and the latest schedule change live in different places. The assigned photographer needs the full brief.</p></article><article><span>02 / IN PRODUCTION</span><h3>Files wait on the next person</h3><p>Photos, video and floor plans can move through different hands. Without a shared job record, it is harder to see what is missing.</p></article><article><span>03 / BEFORE DELIVERY</span><h3>“Is it ready?” becomes a daily question</h3><p>Edits, review notes and approvals need a visible path so the team knows what can be delivered to the client.</p></article></div></div></section>
    <section className="rf-section rf-dark" id="how"><div className="rf-wrap"><div className="rf-section-head"><div><p className="rf-eyebrow">THE JOB JOURNEY</p><h2>Keep the whole job moving.</h2></div><p>As work passes between coordinators, photographers, editors and reviewers, the context stays with the property job.</p></div><div className="rf-steps"><article className="rf-step"><span>01 / 04</span><h3>Create the job</h3><p>Record the client, property, access notes, services and add-ons in one place.</p></article><article className="rf-step"><span>02 / 04</span><h3>Plan the shoot</h3><p>Set the time and assign a photographer with the right job instructions.</p></article><article className="rf-step"><span>03 / 04</span><h3>Move through production</h3><p>Keep source files, editing, review and revisions tied to the job.</p></article><article className="rf-step"><span>04 / 04</span><h3>Deliver with confidence</h3><p>See what is approved and ready for the final client handoff.</p></article></div><div className="rf-workflow-gallery"><figure><Media name="photographer" alt="Property photographer preparing a camera inside a home" sizes="(max-width: 900px) 100vw, 50vw" /><figcaption><strong>On site</strong><span>The photographer gets the brief, property details and services for the shoot.</span></figcaption></figure><figure><Media name="editor" alt="Property media editor reviewing residential photography" sizes="(max-width: 900px) 100vw, 50vw" /><figcaption><strong>In production</strong><span>The team follows files, edits and review back to the same job.</span></figcaption></figure></div></div></section>
    <section className="rf-section rf-story" id="features"><div className="rf-wrap rf-story-grid"><div className="rf-story-media"><Media name="interior2" alt="Bright coastal home interior, representing real estate media work" sizes="(max-width: 900px) 100vw, 50vw" /><div className="rf-caption">From the first brief to the final files</div></div><div className="rf-story-copy"><p className="rf-eyebrow">ONE PLACE FOR DAILY OPERATIONS</p><h2>Run the job without switching between tools to find the answer.</h2><p>Instead of rebuilding the story from an inbox, calendar, spreadsheet and folder, your team follows one property job. The planned workspace keeps its details, people, materials and next action connected.</p><div className="rf-feature-list"><div><h3>Orders and services</h3><p>Keep the client, property, brief, services and add-ons in one job.</p></div><div><h3>Scheduling and assignments</h3><p>Plan the shoot and give the photographer the right instructions.</p></div><div><h3>Files and production</h3><p>Follow source materials and editing work without losing the job context.</p></div><div><h3>Review and delivery</h3><p>Know what needs changes, what is approved and what is ready for the client.</p></div></div></div></div></section>
    <section className="seo-home-links rf-section"><div className="rf-wrap"><p className="rf-eyebrow">EXPLORE BY WORKFLOW</p><h2>Find the part of the job you need to coordinate.</h2><div className="seo-home-grid">
      <Link href="/real-estate-photography-business-software"><strong>Business software</strong><span>Bring the daily work around each property job together. ↗</span></Link>
      <Link href="/real-estate-photography-workflow-software"><strong>Shoot-to-delivery workflow</strong><span>Follow the brief, shoot, production and handoff. ↗</span></Link>
      <Link href="/real-estate-photography-scheduling-software"><strong>Shoot scheduling</strong><span>Keep the time, photographer and property instructions connected. ↗</span></Link>
      <Link href="/real-estate-media-production-management"><strong>Production management</strong><span>See editing, revisions, approval and readiness. ↗</span></Link>
    </div></div></section>
    <SampleJob />
    <ProductionBoard />
    <section className="rf-image-band"><Media name="exterior" alt="Contemporary home photographed at dusk" sizes="100vw" /><div className="rf-image-band-copy"><p className="rf-eyebrow">A WORKSPACE FOR THE WORK BEHIND THE IMAGE</p><h2>Every great listing has a production story.</h2><p>Make every handoff easier to understand, from the shoot request to approved media.</p></div></section>
    <FAQ />
    <section className="rf-section rf-signup" id="early-access"><div className="rf-wrap rf-signup-grid"><div><p className="rf-eyebrow">JOIN EARLY ACCESS</p><h2>Help shape one workspace for shoots and production.</h2><p>We’re inviting growing real estate photography and property media teams in the US and Australia to register interest. Tell us which part of your current workflow takes the most coordination; your input will help shape the first release.</p><div className="rf-fit-note"><strong>Is this your team?</strong><span>You coordinate multiple shoots, people or production handoffs—and you’re tired of reconstructing status from separate tools.</span></div><ul><li>No payment required</li><li>No mandatory sales call</li><li>We’ll contact you about PhotoTrackly early access</li></ul></div><LeadForm variant="footer" /></div></section>
  </main><footer><div className="rf-wrap rf-foot-inner"><Wordmark /><p>Property media work, connected.</p><div className="rf-footer-links"><Link href="/privacy">Privacy</Link><CookieSettingsButton /><a href="#main">Back to top ↑</a></div></div></footer><AnalyticsConsent /></div>;
}
