'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Brand, Eyebrow, Icon, Photo, Tabs, Tag } from '@/components/ui';
import { STAGES } from '@/lib/model';
import EarlyAccess from './early-access';
import MiniWorkspace from './mini-workspace';

const personas = [
  { label: 'Coordinators', tag: 'FOR THE PERSON KEEPING IT ALL TOGETHER', title: 'A clear next step. Not another follow-up.', description: 'Keep the whole day in view without piecing together calendars, folders, and messages.', features: [['board', 'Know where every job stands', 'See the stage, owner, and next action in one place.'], ['calendar', 'Keep the shoot day organized', 'Bring the schedule and photographer assignment together.'], ['message', 'Make handoffs easier to follow', 'Keep instructions with the work, not in a separate thread.']] },
  { label: 'Studio owners', tag: 'FOR THE PERSON BUILDING THE BUSINESS', title: 'Your team’s progress. Not just your inbox.', description: 'A shared operational view, so every question does not have to come back to you.', features: [['eye', 'See the work across the studio', 'Understand active jobs and what needs attention.'], ['people', 'Make responsibility visible', 'Give every next step a clear owner.'], ['layers', 'Build a more dependable handoff', 'Keep context connected as your work gets more complex.']] },
  { label: 'Photographers', tag: 'FOR THE PEOPLE OUT IN THE FIELD', title: 'Arrive ready. Get back to creating.', description: 'Keep the property, access instructions, and requested services together before the shoot begins.', features: [['pin', 'Know where you’re going', 'Find the property, shoot time, and access notes.'], ['camera', 'Know what the job needs', 'See services, add-ons, and the client’s instructions.'], ['upload', 'Leave a clear next step', 'Keep shoot notes and source files with the job.']] },
  { label: 'Editors & reviewers', tag: 'FOR THE PEOPLE BRINGING IT TOGETHER', title: 'Less deciphering. More doing your best work.', description: 'Bring the brief, working files, and feedback into the same job so the next decision is clear.', features: [['folder', 'Start with the right inputs', 'Keep source files and production instructions together.'], ['brush', 'Know who owns the next edit', 'Track the production stage and outstanding work.'], ['checkCircle', 'Give feedback a clear place', 'Record approvals and revision notes against the job.']] },
];
const faqs = [
  ['Is PhotoTrackly available to use today?', 'Not yet. PhotoTrackly is in development. The workspace on this site is an interactive, browser-only product preview with fictional data, not a live SaaS account.'],
  ['What happens when I join early access?', 'Registration records your interest; it does not create an account or guarantee immediate access. No payment or meeting is required. On an unconnected preview, the form clearly saves only a local draft and does not submit a registration.'],
  ['Who is it being built for?', 'Real-estate photography studios and property-media companies coordinating photographers, editors, services, and production handoffs. Our launch focus is the United States and Australia. Coordination complexity matters more than a fixed team size.'],
  ['Does it replace our photographers or editors?', 'No. The first-release direction is a connected operational workspace for the people doing the work. Automated image editing and autonomous quality control are not part of that promise.'],
  ['Will it connect to the tools we already use?', 'Exact integration and replacement scope is still unconfirmed. We are not claiming that every calendar, storage service, gallery, or financial tool already connects to PhotoTrackly.'],
  ['What are the pricing and launch date?', 'Pricing and launch timing have not been established. We are collecting interest and learning about real studio workflows as the product develops.'],
];

export default function Landing({ registrationEnabled }: { registrationEnabled: boolean }) {
  const [menu, setMenu] = useState(false); const [persona, setPersona] = useState(0); const [preview, setPreview] = useState(0); const [stage, setStage] = useState(0);
  const person = personas[persona]; const step = STAGES[stage];
  return <>
    <header className="site-header"><div className="container header-inner"><Brand /><span className="development-label"><span className="dot" />IN DEVELOPMENT</span><nav className="desktop-nav" aria-label="Main navigation"><a href="#workflow">The workflow</a><a href="#people">Built for your team</a><a href="#workspace">Inside the workspace</a></nav><div className="header-actions"><a className="button button-small" href="#early-access">Join early access <Icon name="arrowUp" /></a><button className="icon-button mobile-menu" type="button" aria-label="Toggle navigation" aria-expanded={menu} aria-controls="site-mobile-nav" onClick={() => setMenu(!menu)}><Icon name="menu" /></button></div></div><nav className="mobile-site-nav" id="site-mobile-nav" aria-label="Mobile navigation" hidden={!menu}>{[['#workflow', 'The workflow'], ['#people', 'Built for your team'], ['#workspace', 'Inside the workspace']].map(([href, title]) => <a href={href} key={href} onClick={() => setMenu(false)}>{title}<Icon name="arrow" /></a>)}<Link href="/workspace/pipeline">Explore the preview <Icon name="arrow" /></Link></nav></header>
    <main id="main" className="landing-main">
      <section className="hero"><div className="container"><div className="hero-eyebrow-row"><Eyebrow>THE WORKSPACE BEHIND EVERY PROPERTY SHOOT</Eyebrow><span className="mono hero-edition">BUILT FOR REAL ESTATE MEDIA TEAMS</span></div><div className="hero-copy"><div><h1>Less chasing.<br /><span>More breathing room.</span></h1><p>Every shoot, from booking to delivery. One connected workspace for the people running property media teams.</p></div><div className="hero-cta"><a className="button button-large" href="#early-access">Join early access <Icon name="arrowUp" /></a><Link className="text-link" href="/workspace/pipeline">Explore the workspace preview <Icon name="arrow" /></Link><span className="micro">In development. No payment or meeting required.</span></div></div>
      <div className="value-strip">{[['folder', 'One job', 'Every detail, together'], ['layers', 'A clear next step', 'From booking to delivery'], ['people', 'Your whole team', 'Shared context. Clear ownership.'], ['eye', 'The full picture', 'Less piecing things together']].map(([icon, title, copy], i) => <div className="value-card" key={title}><span className="value-icon"><Icon name={icon} /></span><div><strong>{title}</strong><span>{copy}</span></div><span className="value-number mono">0{i + 1}</span></div>)}</div>
      <div className="hero-gallery"><article className="photo-card ops-photo"><Photo source="coordinator" alt="A coordinator working at a property media studio" priority /><div className="photo-shade" /><div className="photo-label"><Icon name="grid" />THE STUDIO</div><div className="photo-caption"><span className="mono">FOR THE PEOPLE KEEPING IT MOVING</span><h3>Less “where’s that file?”<br />More everything in its place.</h3><span className="glass-tag"><span className="dot" />A clearer kind of workday</span></div></article><article className="photo-card property-photo"><Photo alt="Modern property photographed at twilight beside a reflecting pool" priority /><div className="photo-shade" /><div className="photo-label"><Icon name="camera" />THE WORK</div><span className="sample-label mono">EXAMPLE PROPERTY JOB</span><div className="photo-caption"><span className="mono">PT-0842 · MALIBU, CA</span><h3>740 Ocean View Drive</h3><div className="photo-caption-bottom"><div className="glass-tags">{['Photography', 'Drone', 'Floor plan'].map(x => <span className="glass-tag" key={x}>{x}</span>)}</div><Link href="/workspace/pipeline" className="photo-open" aria-label="Explore the example property job"><Icon name="arrowUp" /></Link></div></div></article><article className="photo-card field-photo"><Photo source="photographer" alt="Property photographer holding a camera stabilizer on location" priority /><div className="photo-shade" /><div className="photo-label"><Icon name="aperture" />THE FIELD</div><div className="photo-caption"><span className="mono">CONTEXT THAT GOES WITH YOU</span><h3>More creating.<br />Less checking in.</h3><span className="glass-tag"><Icon name="check" />The brief, right where you need it</span></div></article></div><div className="hero-footnote"><span>Good work deserves a smoother way to get there.</span><a href="#workflow">See how it comes together <Icon name="down" /></a></div></div></section>
      <section className="section section-tint" id="people"><div className="container"><div className="section-heading"><div><Eyebrow orange icon="heart">PEOPLE FIRST. ALWAYS.</Eyebrow><h2>Built around the people<br />doing the work.</h2></div><p>Not another dashboard to keep up with.<br />A shared place to keep the work moving.</p></div><div className="people-layout"><div className="people-image"><Photo source="team" alt="A coordinator and photographer discussing work in a bright studio" /><div className="photo-shade" /><span className="corner-mark top-left" /><span className="corner-mark bottom-right" /><div className="people-image-caption"><span className="mono">THE TEAM BEHIND THE PROPERTY</span><h3>A little less chasing.<br />A lot more on the same page.</h3></div></div><div className="people-content"><Tabs labels={personas.map(p => p.label)} index={persona} onChange={setPersona} prefix="persona" label="Your role" className="persona-tabs" /><div id="persona-panel" role="tabpanel" aria-labelledby={`persona-tab-${persona}`} className="persona-panel"><span className="mono persona-kicker">{person.tag}</span><h3>{person.title}</h3><p>{person.description}</p><div className="persona-features">{person.features.map(([icon, title, copy]) => <div key={title}><span className="feature-icon"><Icon name={icon} /></span><div><h4>{title}</h4><p>{copy}</p></div></div>)}</div></div></div></div><div className="before-after-grid">{[['“Who’s shooting this one?”', 'A named photographer. A shared schedule.'], ['“Did the editor get the notes?”', 'The brief travels with the property job.'], ['“Is this ready for the client?”', 'A visible review status and next action.']].map(([before, after]) => <div className="before-after" key={before}><span className="mono muted">SOUND FAMILIAR?</span><p>{before}</p><div><Icon name="arrow" /><span>{after}</span></div></div>)}</div></div></section>
      <section className="section workspace-section" id="workspace"><div className="container"><div className="section-heading"><div><Eyebrow orange icon="grid">A CLOSER LOOK</Eyebrow><h2>Your day, without<br />the detective work.</h2><p>See the job. Know the owner. Find the next step.</p></div><Link href="/workspace/pipeline" className="button button-outline">Open interactive preview <Icon name="arrowUp" /></Link></div><div className="workspace-showcase"><div className="showcase-top"><Tabs labels={['Job pipeline', 'Shoot schedule', 'Media review']} index={preview} onChange={setPreview} prefix="preview" label="Product preview" className="showcase-tabs" /><span className="mono preview-caption"><span className="dot" />ILLUSTRATIVE PRODUCT PREVIEW</span></div><div id="preview-panel" role="tabpanel" aria-labelledby={`preview-tab-${preview}`}><MiniWorkspace view={preview} /></div></div><div className="showcase-features">{[['folder', 'Job details, connected', 'Property, client, services, notes, and files.'], ['user', 'A person behind every step', 'Clear assignments, not another group thread.'], ['checkCircle', 'A handoff you can follow', 'From source files to approved deliverables.']].map(([icon, title, copy]) => <div key={title}><Icon name={icon} /><div><strong>{title}</strong><p>{copy}</p></div></div>)}</div></div></section>
      <section className="section flow-section"><div className="container"><div className="flow-canvas"><div className="flow-heading"><div><Eyebrow orange icon="link">CONNECTED FROM THE START</Eyebrow><h2>One property job.<br />No loose ends.</h2></div><p>Different people. Different stages.<br />The same context, all the way through.</p></div><div className="handoff-flow">{STAGES.map((s, i) => <div className="handoff-step" key={s.name}><span className="handoff-number mono">0{i + 1}</span><div className="handoff-icon"><Icon name={s.icon} /></div><h3>{s.short}</h3><span>{s.owner}</span>{i < 5 && <div className="handoff-arrow"><Icon name="arrow" /></div>}</div>)}</div><div className="flow-baseline"><div><Icon name="folder" /><span>PROPERTY · CLIENT · SERVICES · NOTES · FILES</span></div><span className="mono">ONE CONNECTED WORKSPACE</span></div></div></div></section>
      <section className="section field-section"><div className="container"><div className="field-layout"><div className="field-visual"><Photo source="photographer" alt="Photographer working with a stabilizer during a property shoot" /><div className="field-vignette" /><div className="mobile-brief"><div className="mobile-brief-head"><span className="brand-mark"><Icon name="camera" /></span><span className="mono">ON THE SHOOT</span><span className="dot" /></div><span className="mono muted">PT-0842 · EXAMPLE BRIEF</span><h3>740 Ocean<br />View Drive</h3><div className="brief-time"><Icon name="clock" />Tuesday, 9:00 AM</div><div className="brief-divider" />{[['Photography', 'Full property coverage'], ['Drone imagery', 'Exterior & surroundings'], ['Floor plan', 'Include all living spaces']].map(([title, copy]) => <div className="brief-check" key={title}><Icon name="checkCircle" /><span>{title}<small>{copy}</small></span></div>)}<div className="brief-note"><Icon name="pin" /><span>Meet the agent at the front gate.</span></div></div><span className="field-visual-caption mono">ILLUSTRATIVE MOBILE BRIEF</span></div><div className="field-content"><Eyebrow orange icon="phone">FROM THE DESK TO THE DOORSTEP</Eyebrow><h2>The brief goes<br />where the shoot goes.</h2><p>Give photographers the context they need, before they need to ask. Keep the property, timing, services, and instructions in the same place.</p><div className="persona-features">{[['pin', 'The right address. The right access.', 'Property details and agent instructions, together.'], ['camera', 'A shared understanding of the shoot.', 'Requested services and special notes, in view.'], ['folder', 'An easier next handoff.', 'Keep source files and shoot context connected.']].map(([icon, title, copy]) => <div key={title}><span className="feature-icon"><Icon name={icon} /></span><div><h4>{title}</h4><p>{copy}</p></div></div>)}</div><Link href="/workspace/schedule" className="text-link">Explore the shoot schedule <Icon name="arrow" /></Link></div></div></div></section>
      <section className="section section-tint" id="workflow"><div className="container"><div className="section-heading"><div><Eyebrow orange icon="layers">FOLLOW ONE PROPERTY JOB</Eyebrow><h2>Six stages. One connected story.</h2><p>A representative workflow, from the first details to the final handoff.</p></div><Tag>EXAMPLE JOB · PT-0842</Tag></div><Tabs labels={STAGES.map((s, i) => `0${i + 1}  ${s.short}`)} index={stage} onChange={setStage} prefix="workflow" label="Property media workflow" className="workflow-tabs" /><div id="workflow-panel" className="workflow-panel" role="tabpanel" aria-labelledby={`workflow-tab-${stage}`}><div className="workflow-content"><div className="workflow-description"><Tag tone="orange">{step.name}</Tag><h3>{step.title}</h3><p>{step.description}</p><div className="workflow-owner"><Icon name="user" /><span className="mono">OWNERSHIP</span><strong>{step.owner}</strong></div></div><div className="workflow-example"><div className="workflow-example-title"><span className="mono">JOB DETAILS / 0{stage + 1}</span><Icon name={step.icon} /></div>{step.fields.map(([label, value]) => <div className="workflow-field" key={label}><span>{label}</span><strong>{value}</strong></div>)}<span className="workflow-example-note mono">SAMPLE DATA · ILLUSTRATIVE WORKFLOW</span></div></div><div className="workflow-panel-footer"><span className="mono">0{stage + 1} <span className="muted">/ 06</span></span><div><button type="button" className="icon-button" aria-label="Previous workflow stage" disabled={stage === 0} onClick={() => setStage(stage - 1)}><Icon name="arrow" className="flip" /></button>{stage < 5 ? <button type="button" className="text-link" onClick={() => setStage(stage + 1)}>Next: {STAGES[stage + 1].short} <Icon name="arrow" /></button> : <Link className="text-link" href="/workspace/pipeline">Explore the workspace <Icon name="arrow" /></Link>}</div></div></div></div></section>
      <section className="section audience-section"><div className="container"><div className="section-heading centered"><Eyebrow orange icon="people">MADE FOR THE WAY YOUR TEAM WORKS</Eyebrow><h2>When the work grows,<br />the chasing shouldn’t.</h2><p>It’s about coordination complexity, not a minimum number of shoots.</p></div><div className="audience-grid"><article className="audience-card good-fit"><Icon name="checkCircle" /><h3>A good fit for</h3><div className="fit-items">{[['Property-media studios', 'Several photographers, editors, or production handoffs.'], ['Growing operational complexity', 'Even a small team can outgrow scattered tools.'], ['Multi-service property jobs', 'Photography, video, drone, floor plans, and more.'], ['US & Australian teams', 'Our initial customer-discovery and launch focus.']].map(([title, copy]) => <div key={title}><h4>{title}</h4><p>{copy}</p></div>)}</div></article><article className="audience-card"><Icon name="info" /><h3>Not what we’re building</h3><div className="fit-items">{[['A property marketplace', 'This is for the business making the media.'], ['An AI image editor', 'The workflow supports your human creative team.'], ['A lead-generation tool', 'The focus is coordinating work already coming in.'], ['A promise to connect everything', 'Exact integration scope is still unconfirmed.']].map(([title, copy]) => <div key={title}><h4>{title}</h4><p>{copy}</p></div>)}</div></article></div></div></section>
      <section className="section section-tint early-section" id="early-access"><div className="container"><div className="early-card"><div className="early-copy"><Eyebrow orange icon="spark">HELP SHAPE WHAT COMES NEXT</Eyebrow><h2>More room<br />for good work.</h2><p>We’re building PhotoTrackly with property-media teams in mind. Tell us a little about your studio and be part of the early-access interest list.</p><div className="early-expectation"><span className="mono">WHAT TO EXPECT</span><p>Register your interest. Share your workflow, only when you’re ready. Hear about access as the product develops.</p></div><span className="early-disclaimer"><Icon name="lock" />No payment. No required meeting.<br />Registration does not create a software account.</span></div><div className="early-form-wrap"><EarlyAccess enabled={registrationEnabled} /></div></div></div></section>
      <section className="section faq-section" id="faq"><div className="container faq-container"><div className="section-heading centered"><Eyebrow orange icon="message">A FEW THINGS WORTH KNOWING</Eyebrow><h2>Good questions. Clear answers.</h2></div><div className="faq-list">{faqs.map(([question, answer]) => <details className="faq-item" name="phototrackly-faq" key={question}><summary>{question}<Icon name="plus" /></summary><p>{answer}</p></details>)}</div></div></section>
    </main><footer className="site-footer"><div className="container"><div className="footer-grid"><div><Brand /><p>A connected shoot-to-delivery workspace<br />for real-estate media teams.</p><Tag>IN DEVELOPMENT</Tag></div><div><span className="mono">THE WORKSPACE</span><Link href="/workspace/pipeline">Job pipeline</Link><Link href="/workspace/schedule">Shoot schedule</Link><Link href="/workspace/review">Media review</Link><Link href="/workspace/delivery">Client delivery</Link></div><div><span className="mono">GET TO KNOW US</span><a href="#people">Built for your team</a><a href="#workflow">The workflow</a><a href="#faq">Questions & answers</a><a href="#early-access">Join early access</a></div><div><span className="mono">BUILT WITH INTENTION</span><p>For the people behind<br />every property shoot.</p><p className="micro">Launch focus: United States & Australia.<br />All product screens and job data are illustrative.</p></div></div><div className="footer-bottom"><span>© 2026 PhotoTrackly</span><span>Less chasing. More breathing room.</span><a href="#main">Back to top <Icon name="arrowUp" /></a></div></div></footer>
  </>;
}
