'use client';
import Link from 'next/link';
import { Avatar, Icon, Photo } from '@/components/ui';
import { seedJobs, STAGES, TEAM, VIEWS } from '@/lib/model';

const sample = seedJobs();
export default function MiniWorkspace({ view }: { view: number }) {
  const route = ['pipeline', 'schedule', 'review'][view];
  return <div className="mini-app"><aside className="mini-sidebar"><span className="mini-logo"><Icon name="camera" />PhotoTrackly<span>.</span></span><div className="mini-studio"><Avatar name="Northlight Studio" small /><span>Northlight Studio<small>Example workspace</small></span></div><span className="mono mini-nav-label">WORKSPACE</span>{Object.entries(VIEWS).map(([key, title], i) => <Link key={key} href={`/workspace/${key}`} className={i === view ? 'active' : ''}><Icon name={['board', 'calendar', 'eye', 'send'][i]} />{title}</Link>)}<span className="mini-local-note"><Icon name="info" />Sample data only</span></aside><div className="mini-main"><div className="mini-toolbar"><span>Workspace <span>/</span> {['Pipeline overview', 'Shoot schedule', 'Media review'][view]}</span><Avatar name="Alex Morgan" small /></div><div className="mini-main-content"><div className="mini-main-heading"><div><h3>{['A clearer view of your day.', 'A place for everyone.', 'Good work, ready to go.'][view]}</h3><p>{['Every job. Every handoff. Right where you need it.', 'See who is going where, and what they need to know.', 'A human review, with clear next steps.'][view]}</p></div><Link href={`/workspace/${route}`} className="mini-button"><Icon name="expand" />Explore</Link></div>
  {view === 0 && <><div className="mini-metrics">{[['Active jobs', sample.filter(j => j.stage < 5).length], ['On the schedule', sample.filter(j => j.stage === 1).length], ['Awaiting review', sample.filter(j => j.stage === 4).length], ['Delivered', sample.filter(j => j.stage === 5).length]].map(([name, value], i) => <div key={name}><span>{name}</span><strong>{value}<Icon name={['folder', 'calendar', 'eye', 'checkCircle'][i]} /></strong></div>)}</div><div className="mini-board">{[0, 1, 3, 4].map(stage => <div className="mini-column" key={stage}><div className="mini-column-title"><span className={`dot stage-dot-${stage}`} />{STAGES[stage].name}<span>{sample.filter(j => j.stage === stage).length}</span></div>{sample.filter(j => j.stage === stage).map((job, i) => <Link href="/workspace/pipeline" className={`mini-job ${i ? 'secondary-mini' : ''}`} key={job.id}>{!i && <Photo alt={`Illustrative property photograph for ${job.address}`} />}<span className="mono">{job.id}</span><h4>{job.address}</h4><p>{job.city}</p>{!i && <div className="mini-service">{job.services.join(' · ')}</div>}<div className="mini-job-footer"><Avatar name={job.photographer} small /><span>{job.photographer || 'Unassigned'}</span></div></Link>)}</div>)}</div></>}
  {view === 1 && <><div className="mini-schedule-date"><Icon name="calendar" />Tuesday, September 15 <span className="mono">EXAMPLE SCHEDULE</span></div><div className="mini-calendar">{TEAM.slice(0, 3).map((name, i) => <div className="mini-calendar-col" key={name}><div><Avatar name={name} small />{name}</div><Link href="/workspace/schedule" className={`mini-calendar-event event-${i}`}><span className="mono">{['09:00 — 10:00', '10:30 — 11:30', '14:00 — 15:00'][i]}</span><strong>{[sample[0].address, sample[1].address, sample[3].address][i]}</strong><span>Photography + property media</span><small><Icon name="pin" />View property brief <Icon name="arrow" /></small></Link></div>)}</div></>}
  {view === 2 && <div className="mini-review"><div className="mini-review-photo"><Photo alt="Illustrative property photo in a human review interface" /><span className="mini-photo-count mono">EXTERIOR_01.JPG · EXAMPLE IMAGE</span></div><div className="mini-review-checks"><span className="mono">HUMAN QUALITY REVIEW</span><h4>740 Ocean View Drive</h4><p>A considered final look.</p>{['Coverage & composition', 'Verticals & alignment', 'Color & exposure', 'File names & package'].map((text, i) => <div key={text}><Icon name={i < 3 ? 'checkCircle' : 'eye'} />{text}</div>)}<Link href="/workspace/review" className="mini-button">Open review <Icon name="arrow" /></Link></div></div>}
  </div></div></div>;
}
