'use client';
import { useState, type KeyboardEvent } from 'react';
import { track } from '@/lib/analytics';
import { Concept, Glyph, Kicker } from './primitives';
import { Media } from './media';

const stages = [
  { name: 'Brief', icon: 'order', status: 'Order received', title: 'Start with the whole picture.', copy: 'The client, property, services, and access notes become one shared job. No rebuilding the brief from separate messages.', owner: 'Alex · Coordinator', initials: 'AL', next: 'Confirm the shoot time and assign a photographer.', fields: [['Services', 'Photography · Drone · Floor plan'], ['Client brief', 'Show the open living spaces and garden.'], ['Access', 'Meet the agent at the front gate.']], checks: ['Client and property recorded', 'Requested services selected', 'Access instructions attached'] },
  { name: 'Shoot', icon: 'camera', status: 'Shoot scheduled', title: 'Give the shoot a clear owner.', copy: 'The photographer gets the timing, property instructions, and requested services in the same job record.', owner: 'Sam · Photographer', initials: 'SA', next: 'Complete the shoot and attach the source files.', fields: [['Scheduled time', 'Tuesday · 9:00–10:30 AM'], ['Assignment', 'Sam · Manually assigned by Alex'], ['Shoot note', 'Garden first; agent will open the side gate.']], checks: ['Photographer assigned manually', 'Shoot time confirmed', 'Brief available on the job'] },
  { name: 'Production', icon: 'folder', status: 'Editing in progress', title: 'The files keep their context.', copy: 'Source materials, editing instructions, and the next handoff stay attached to the property—not buried in a folder name.', owner: 'Jamie · Editor', initials: 'JA', next: 'Finish the photo edits and send the set for review.', fields: [['Photo set', 'Source files received · Editing in progress'], ['Floor plan', 'Prepared · Waiting for review'], ['Production note', 'Keep window views natural and consistent.']], checks: ['Source materials received', 'Editing owner identified', 'Review is the next handoff'] },
  { name: 'Delivery', icon: 'delivery', status: 'Approved for delivery', title: 'Send what is actually ready.', copy: 'Review notes are resolved and the approved deliverables are visible together before the coordinator hands them to the client.', owner: 'Alex · Coordinator', initials: 'AL', next: 'Deliver the approved media to the client.', fields: [['Photo set', 'Reviewed and approved'], ['Drone + floor plan', 'Reviewed and approved'], ['Open review notes', 'None in this illustrative job']], checks: ['Review completed', 'Approved media identified', 'Client handoff is next'] },
];
export default function SampleJob() {
  const [index, setIndex] = useState(0); const stage = stages[index];
  function change(next: number) { setIndex(next); track('sample_stage_view', { stage: stages[next].name }); }
  function keyboard(event: KeyboardEvent<HTMLButtonElement>, current: number) {
    if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return;
    event.preventDefault();
    const next = event.key === 'Home' ? 0 : event.key === 'End' ? stages.length - 1 : (current + (event.key === 'ArrowRight' ? 1 : -1) + stages.length) % stages.length;
    change(next); document.getElementById(`job-tab-${next}`)?.focus();
  }
  return <section id="sample-job" className="pl-section pl-sample"><div className="pl-wrap"><div className="pl-section-heading"><div><Kicker>ONE PROPERTY. EVERY HANDOFF.</Kicker><h2>Follow the job.<br /><em>Not the message thread.</em></h2></div><p>Choose a stage. See the context, the owner, and what happens next.<br /><span className="pl-small">Illustrative concept, not a live customer job or product screenshot.</span></p></div><div className="pl-job-shell"><div className="pl-job-top"><span><Glyph name="folder" /> THE SHARED JOB RECORD</span><Concept /></div><div className="pl-job-tabs" role="tablist" aria-label="Sample job stages">{stages.map((s, i) => <button type="button" key={s.name} role="tab" id={`job-tab-${i}`} aria-controls="sample-job-panel" aria-selected={index === i} tabIndex={index === i ? 0 : -1} onClick={() => change(i)} onKeyDown={event => keyboard(event, i)}><span className="pl-step-index">0{i + 1}</span><Glyph name={s.icon} />{s.name}<span className="pl-tab-arrow"><Glyph name="arrow" /></span></button>)}</div><div className="pl-job-panel" id="sample-job-panel" role="tabpanel" tabIndex={0} aria-labelledby={`job-tab-${index}`}><div className="pl-job-property"><div className="pl-job-photo"><Media name="exterior" alt="A contemporary white home with a garden and covered outdoor living area" sizes="(max-width: 760px) 90vw, 32vw" /><span className="pl-image-label">EXAMPLE PROPERTY</span></div><div className="pl-job-address"><span className="pl-overline">PT–0042 · ILLUSTRATIVE JOB</span><h3>42 Bay Street</h3><p>Photography · Drone · Floor plan</p><div className="pl-owner"><span className="pl-person">{stage.initials}</span><div><span>RESPONSIBLE PERSON</span><strong>{stage.owner}</strong></div></div></div></div><div className="pl-job-detail"><span className={`pl-status pl-status-${index}`}><span />{stage.status}</span><h3>{stage.title}</h3><p>{stage.copy}</p><dl className="pl-context">{stage.fields.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="pl-next"><Glyph name="arrow" /><div><span>NEXT ACTION</span><strong>{stage.next}</strong></div></div><div className="pl-checks">{stage.checks.map(check => <span key={check}><Glyph name="check" />{check}</span>)}</div></div></div><div className="pl-job-bottom"><span><Glyph name="lock" />The context stays with the job, whoever picks it up next.</span><span>Planned workflow · Features may change</span></div></div></div></section>;
}
