'use client';
import { useState, type KeyboardEvent } from 'react';
import { track } from '@/lib/analytics';
const stages = [
  { name: 'Brief', status: 'Order received', title: 'The request becomes a job', copy: 'The property, client, services, access notes and requested date travel together.', owner: 'Coordinator', next: 'Schedule the shoot', checks: ['Client and property recorded', 'Photography, drone and floor plan selected', 'Access instructions attached'] },
  { name: 'Shoot', status: 'Shoot scheduled', title: 'The photographer has the brief', copy: 'The time, property instructions and selected services stay with the same job record.', owner: 'Photographer', next: 'Complete the shoot and attach source files', checks: ['Photographer assigned manually', 'Shoot time confirmed', 'Property access and services in the brief'] },
  { name: 'Production', status: 'Editing in progress', title: 'The files keep their context', copy: 'Source materials, editing instructions and review stay connected to the property job.', owner: 'Editor', next: 'Send the edited media for review', checks: ['Source materials received', 'Editing owner identified', 'Review is the next handoff'] },
  { name: 'Delivery', status: 'Approved for delivery', title: 'Approved media is ready to hand over', copy: 'Review notes are resolved and the approved deliverables are visible together before the client handoff.', owner: 'Coordinator', next: 'Deliver the approved media', checks: ['Review completed', 'Approved media identified', 'Client handoff is next'] },
];
export default function SampleJob() {
  const [index, setIndex] = useState(0); const stage = stages[index];
  function change(next: number) { setIndex(next); track('sample_stage_view', { stage: stages[next].name }); }
  function keyboard(event: KeyboardEvent<HTMLButtonElement>, current: number) {
    if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return;
    event.preventDefault();
    const next = event.key === 'Home' ? 0 : event.key === 'End' ? stages.length - 1 : (current + (event.key === 'ArrowRight' ? 1 : -1) + stages.length) % stages.length;
    change(next); document.getElementById(`job-tab-${next}`)?.focus();
  }
  return <section id="sample-job" className="rf-section rf-job-detail"><div className="rf-wrap"><div className="rf-section-head"><div><p className="rf-eyebrow">EXPLORE A SAMPLE JOB</p><h2>Follow one property through the handoffs.</h2></div><p>Choose a stage to see the planned context, owner and next action. This is an illustrative concept, not a live customer job.</p></div><div className="rf-job-detail-grid"><div className="rf-walkthrough"><div className="rf-walkthrough-tabs" role="tablist" aria-label="Sample job stages">{stages.map((s,i) => <button key={s.name} type="button" className="rf-walkthrough-trigger" role="tab" id={`job-tab-${i}`} aria-controls="sample-job-panel" aria-selected={i === index} data-state={i === index ? 'active' : 'inactive'} tabIndex={i === index ? 0 : -1} onClick={() => change(i)} onKeyDown={e => keyboard(e,i)}>0{i + 1} {s.name}</button>)}</div><div id="sample-job-panel" role="tabpanel" tabIndex={0} aria-labelledby={`job-tab-${index}`} className="rf-walkthrough-body"><div className="rf-walkthrough-title"><span>42 BAY STREET · ILLUSTRATIVE JOB</span><span className="rf-badge">{stage.status}</span></div><h3>{stage.title}</h3><p>{stage.copy}</p><div className="rf-walkthrough-info"><div><small>RESPONSIBLE PERSON</small><strong>{stage.owner}</strong></div><div><small>NEXT ACTION</small><strong>{stage.next}</strong></div></div><ul>{stage.checks.map(check => <li key={check}><span aria-hidden="true">✓</span>{check}</li>)}</ul></div></div><div className="rf-job-detail-copy">{[['One brief for the whole team','Property details, services, notes and timing stay connected to the same order.'],['A named owner for each step','Photographers, editors and reviewers can see what they are responsible for.'],['Readiness you can check','Track materials and review before approved files move to delivery.']].map(([title,copy]) => <div className="rf-mini-rule" key={title}><b>{title}</b><p>{copy}</p></div>)}<a className="rf-underline" href="#early-access" data-track="cta_click" data-location="sample">Tell us how your team handles this →</a><p className="rf-mocknote">Illustrative product concept. Features are planned and may change before release.</p></div></div></div></section>;
}
